### ISSUE TITLE
IllegalStateException: Not allowed to start service in background

### ISSUE THREAD

**Issue by gajicm93** [Estimote/Android-Fleet-Management-SDK#277]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version >= 4.4 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 1.4.1

**Android devices affected:** Galaxy S8

**Android OS version affected:** Android 8.0

**Beacon hardware version:** Will check tomorrow

## Description

Got this crash from Crashlytics in the wild, can't reproduce it myself. But this is a well known change for Android Oreo, where you can no longer start services from background. Read more [here](https://developer.android.com/about/versions/oreo/background.html#services). My app targets API 27.

**Expected behavior:** not to crash

**Actual behavior:** crashes

## Logs and code
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.estimote.coresdk.scanning.scheduling.SystemAlarmManager$AlarmBroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.coke.tastly/com.estimote.coresdk.service.BeaconService }: app is in background uid UidRecord{fd37547 u0a189 RCVR bg:+1m0s285ms idle procs:1 seq(36,36,36)}
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3397)
       at android.app.ActivityThread.-wrap18(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by iernie** [comment]
I am also seeing this crash popup from some users. Huawei and Samsung devices.

**Comment by gajicm93** [comment]
Is there any ETA for the fix?

**Comment by mihir-elite** [comment]
Hello,

i'm facing the same issue, any resolution on this ?

**Comment by pawelDylag** [comment]
Hello guys, 

This problem affects phones with Android 8.0+ I suppose. This SDK is no longer being maintained, thus there is no support for Oreo+ phones in it. I really encourage you to switch to our currently being developed [ProximitySDK](https://github.com/Estimote/Android-Proximity-SDK) 🚀  - it supports all Android devices since 5.0, and is well prepared for background-work changes introduced in Android 8.0. Plus the API is way easier to use and lets you avoid many common problems :)

Regards, 
Paweł

**Comment by heypiotr** [comment]
_[Cleaning up stale issues following the rebranding of Estimote SDK to Estimote Fleet Management SDK]_

As Pawel mentioned, for proximity detection (enter/exit events), we're asking developers to migrate to our Proximity SDK:

https://developer.estimote.com/proximity/android-tutorial/

If you need any help with the migration, let us know on our forums:

https://forums.estimote.com
