### ISSUE TITLE
Getting ANR Issue

### ISSUE THREAD

**Issue by Veer50** [Estimote/Android-Fleet-Management-SDK#282]
# **Basic Info**
Getting ANR Issue

Estimote SDK version:1.4.1

**Android devices affected:Samsung s7

**Android OS version affected: 7.0 Nougat

**Beacon hardware version: F3.3

**Getting this error after updating version to 1.4.1. App get crashed after few minutes. But i am 
    getting the notifications properly.  Please let me know where I did mistake.

# **In  Log**
**ANR in InMyProject  Reason: Broadcast of Intent { flg=0x14 
   cmp=InMyProject/com.estimote.coresdk.scanning.scheduling.SystemAlarmManager$ 
   AlarmBroadcastReceiver launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has 
   extras) } Load: 6.59 / 6.35 / 6.2

**Comment by heypiotr** [comment]
_[Cleaning up stale issues following the rebranding of Estimote SDK to Estimote Fleet Management SDK]_

Feel free to re-open this issue if the problem still persists with the latest version of the SDK, and affects the fleet management APIs (BulkUpdater, connecting to beacons and changing settings, etc.).

For enter/exit events, we're asking developers to migrate to our Proximity SDK:

https://developer.estimote.com/proximity/android-tutorial/

If you need any help with the migration, let us know on our forums:

https://forums.estimote.com
