### ISSUE TITLE
Doesn't find Beacons unless Estimote App is open

### ISSUE THREAD

**Issue by andre-paulo98** [Estimote/Android-Fleet-Management-SDK#286]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version >= 4.4 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** `1.4.1`

**Android devices affected:** WIKO U FELL LITE

**Android OS version affected:** `6.0`

## Description

I've been trying to use the new SDK (Proximity) and this one, none of them seems to work on my case.
onBeaconsDiscovered is always returning me a empty list with beacons.
Once I open the Estimote App and hit Devices, the list returns 7 beacons. Once I close the app a few moments later the list starts to decrease, until it reaches 0 again.
Code is attached bellow.

## Logs and code
```
protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        SystemRequirementsChecker.checkWithDefaultDialogs(this);

        manager = new BeaconManager(getApplicationContext());
        manager.connect(new BeaconManager.ServiceReadyCallback() {
            @Override
            public void onServiceReady() {
                BeaconRegion region = new BeaconRegion("MyRegion", UUID.fromString("B9407F30-F5F8-466E-AFF9-25556B57FE6D"), null,null);
                manager.startRanging(region);
                manager.setRangingListener(new BeaconManager.BeaconRangingListener() {
                    @Override
                    public void onBeaconsDiscovered(BeaconRegion beaconRegion, List<Beacon> beacons) {
                        System.out.println(beacons.size() + " <<< Beacons Size");
                    }
                });
            }
        });


    }
```

**Comment by android-bash** [comment]
I am facing the same issue in Nokia (Android version 9).
Estimote SDK Version : 1.4.5
After few hours of scan i get empty beacons. And again when i open my app it will give me nearby list of beacons. 

What is the cause and what is the solution?

**Comment by heypiotr** [comment]
_[Cleaning up stale issues following the rebranding of Estimote SDK to Estimote Fleet Management SDK]_

For enter/exit events, we're asking developers to migrate to our Proximity SDK:

https://developer.estimote.com/proximity/android-tutorial/

If you need any help with the migration, let us know on our forums:

https://forums.estimote.com

If this issue also affect the Proximity SDK, feel more than welcome to open a bug report on the Proximity SDK's issue tracker:

https://github.com/estimote/android-proximity-sdk/issues
