### ISSUE TITLE
Xamarin Estimote SDK -0.11.0 for Android version -7 is not scanning beacons (in Visual Studio -2017) 

### ISSUE THREAD

**Issue by AjayDamco** [Estimote/Android-Fleet-Management-SDK#289]
## Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version = 7.0.0
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:**  Xamarin Estimote Android- 0.11.0

**Android devices affected:** Moto C Pluse 

**Android OS version affected:** 7

**Beacon hardware version:** [Paste here your beacons hardware version (you can check that in Estimote Cloud).] 

## Description

I have the same problem with Xamarin Estimote android sdk-0.11.0.(in visual studio -2017)
Beacon scanning is working and detecting beacons in Android version below- 6, but in android version 7.0 or above OnBeaconsDiscovered() and StartRangingBeacons() both are scanning or running/executing but unable-to find any beacons even I am near to beacon I always have beacon count 0.

(It is working for other version of Android).

I am using Xamarin Estimote SDK for development in C# not for Java and there is only few version of SDK available for Xamarin.
**Please see the attachment for more details.**

![xamarin extimote sdk](https://user-images.githubusercontent.com/13217744/42440749-397cdf64-8384-11e8-936f-fed90c0e7c76.png)

## Logs and code
```
Add here any logs, stack traces, code snippets you want to attach, or any other info, like pictures for example
```

**Comment by AjayDamco** [comment]
Hi pawelDylag,

As discussed, I tried the updated version of Xamarin Estimote SDK-1.0.3 , but in this case i unable to get the proximity of beacons as in case of earlier version:

  var beaconAccuracy = Utils.ComputeAccuracy(beacon);
 Utils.Proximity uProximity = Utils.ProximityFromAccuracy(beaconAccuracy);

how I get it in latest version?

Thanks,
Ajay

**Comment by heypiotr** [comment]
You can try our Xamarin binding for the Proximity SDK:

https://www.nuget.org/packages/Estimote.Android.Proximity/
