### ISSUE TITLE
Can't Update when there are too many beacons( More than 100)

### ISSUE THREAD

**Issue by Atul141** [Estimote/Android-Fleet-Management-SDK#290]
I have over 100 beacons in my place. If there only 5 beacons in one place it works properly, but when there are more than 100 beacons, it doesn't work at all.

**Comment by heypiotr** [comment]
_[Cleaning up stale issues following the rebranding of Estimote SDK to Estimote Fleet Management SDK]_

Feel free to re-open this issue if the problem still persists with the latest version of the SDK. If it does, we'd also appreciate more details: the smartphone model, Android version, full output from logcat (you can put it on https://pastebin.com and link to it here), your code or at least which APIs you're using.
