### ISSUE TITLE
SDK and Estimote official app do not detect on Android 9.0 preview

### ISSUE THREAD

**Issue by jamesem** [Estimote/Android-Fleet-Management-SDK#292]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version >= 4.4 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** 1.4.1

**Android devices affected:** Pixel 2 XL

**Android OS version affected:** Android 9.0 Preview Beta 3

**Beacon hardware version:** Unknown exactly, 2 recent location beacons and 1 proximity beacon

## Description

The Estimote SDK does not detect any beacons while ranging.
The official Estimote app also does not detect any beacons while searching in 'configuration'

**(Optional) Steps to reproduce:**

1. Install the Android 9.0 Preview Beta 3
2. Install the official Estimote app from Google Play
3. To go 'configuration', and wait forever for a beacon to appear

**Expected behavior:** beacons appear in the ranged list

**Actual behavior:** 0 beacons appear in the ranged list

## Logs and code
```
Add here any logs, stack traces, code snippets you want to attach, or any other info, like pictures for example
```

**Comment by heypiotr** [comment]
_[Cleaning up stale issues following the rebranding of Estimote SDK to Estimote Fleet Management SDK]_

Feel free to re-open this issue if the problem still persists with the latest version of the SDK, and affects the fleet management APIs (BulkUpdater, connecting to beacons and changing settings, etc.).

For enter/exit events, we're asking developers to migrate to our Proximity SDK:

https://developer.estimote.com/proximity/android-tutorial/

If you need any help with the migration, let us know on our forums:

https://forums.estimote.com
